project:
  type: website
  output-dir: docs

website:
  title: "Joachim Goedhart | Homepage"
  site-url: https://joachimgoedhart.github.io/
  open-graph: true
  favicon: mTq2-Chainbows.png
  navbar:
    right:
      - tools.qmd
      - publications.qmd
      - movies.qmd
      - photos.qmd
      - contact.qmd
  page-footer:
    background: dark
    center: Joachim Goedhart - 2023</br>Made with [Quarto](https://quarto.org/docs/websites/)
    right:
      - icon: github
        href: https://github.com/JoachimGoedhart/JoachimGoedhart.github.io
  twitter-card:
    creator: "@joachimgoedhart"
    site: "@joachimgoedhart"
    image: mTq2-Chainbows.png
format:
  html:
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    toc: false



